#!/bin/sh


### Helpers

log() {
    tag="[null]"
    if [ $1 = 0 ]; then
        tag="[INFO]"
    fi
    if [ $1 = 1 ]; then
        tag="[WARN]"
    fi
    if [ $1 = 2 ]; then
        tag="[ERROR]"
    fi

    echo "$tag $2" >&2
 
    if [ $VRDL_LOG_FILE_ENABLE -eq 1 ]; then
        echo "$tag $2" >> "$VRDL_LOG_FILE"
    fi

    return 0
}

prompt() {
    read -p "$1 > " response
    echo "$response"
}

### MAIN

## Set env vars 

. ./.env


echo "|    $(date)    |" >> "$VRDL_LOG_FILE"
log 0 "Begin ..."

printf "\n"

## Add i386 repositories
# Note: These are likely going away soon

log 0 "Adding i386 repositories via dpkg ..."
dpkg --add-architecture i386

log 0 "Running apt update ..."
apt update 

if [ $? = 0 ]; then
	log 0 "Apt update success"
else
	log 2 "Apt update failure"
fi

log 0 "Running apt upgrade ..."

apt upgrade -y

if [ $? = 0 ]; then
	log 0 "Apt upgrade success"
else
	log 2 "Apt upgrade failure"
fi

## Install Deps

log 0 "Installing deps: $VRDL_DEPS ..."

apt install -y $VRDL_DEPS

if [ $? = 0 ]; then
	log 0 "Deps installation success"
else
	log 2 "Deps installation failure"
fi

## Create Standard User

if id "$VRDL_STANDARD_USER" >/dev/null 2>&1; then
	log 0 "Standard user "$VRDL_STANDARD_USER" already exists"
	
else
	log 0 "Adding user: $VRDL_STANDARD_USER ..."
	
	useradd "$VRDL_STANDARD_USER" -m # -m home dir benefits certain processes, such as font cache
	log 0 "Standard User Provisioned"
fi

## Create Dirs

if [ ! -e "$VRDL_BASE_PATH" ]; then
	mkdir "$VRDL_BASE_PATH"
fi

if [ ! -e "$VRDL_GAME_BASE_PATH" ]; then
	mkdir "$VRDL_GAME_BASE_PATH"
fi

if [ ! -e "$VRDL_GAME_DEFAULT_PATH" ]; then
	mkdir "$VRDL_GAME_DEFAULT_PATH"
fi

if [ ! -e "$VRDL_SCRIPTS_PATH" ]; then
	mkdir "$VRDL_SCRIPTS_PATH"
fi

chown "$VRDL_STANDARD_USER":"$VRDL_STANDARD_USER" "$VRDL_BASE_PATH" -R

## Copy runtime scripts to script path

cp "$VRDL_STATUS" "$VRDL_SCRIPTS_PATH"
cp "$VRDL_MONITOR" "$VRDL_SCRIPTS_PATH"
cp "$VRDL_START" "$VRDL_SCRIPTS_PATH"
cp "$VRDL_INIT_DISPLAY" "$VRDL_SCRIPTS_PATH"
cp "$VRDL_RUNNER" "$VRDL_SCRIPTS_PATH"

# ln to bin for convenience
ln "$VRDL_SCRIPTS_PATH/$VRDL_STATUS" /usr/local/bin/
ln "$VRDL_SCRIPTS_PATH/$VRDL_MONITOR" /usr/local/bin/
ln "$VRDL_SCRIPTS_PATH/$VRDL_START" /usr/local/bin/
ln "$VRDL_SCRIPTS_PATH/$VRDL_INIT_DISPLAY" /usr/local/bin/
ln "$VRDL_SCRIPTS_PATH/$VRDL_RUNNER" /usr/local/bin/

## Provision default wine prefix

log 0 "Provisioning default wine prefix for $VRDL_STANDARD_USER ..."
if [ -e "$VRDL_WINE_PREFIX_PATH" ]; then
    log 0 "Wine prefix  already exists ..."
else
    su $VRDL_STANDARD_USER -c "WINEPREFIX=\"$VRDL_WINE_PREFIX_PATH\" wineboot -i"
fi

if [ ! -e "$VRDL_WINE_PREFIX_PATH" ]; then
    log 2 "Failed to create default wine prefix" 
    log 2 "Exiting ..."
    return 1
fi

# Band-aid fix; dedi auto process needs at least one profile to exist
# or profile selection is presented

log 0 "Creating null_prf.ini to fix automation bug ..."
scctv_profile_dir="$VRDL_WINE_PREFIX_PATH/drive_c/ProgramData/Ubisoft/Tom Clancy's Splinter Cell Chaos Theory/Saved Games/Versus"
su "$VRDL_STANDARD_USER" -c "mkdir -p \"$scctv_profile_dir\""
su "$VRDL_STANDARD_USER" -c "touch \"$scctv_profile_dir\"/null_prf.ini"

## Acquire Game Content

tempdir=temp
tempdir_x="$tempdir/extracted"
mkdir "$tempdir_x" -p

if [ "$VRDL_LATEST_CONTENT_ENABLE" -eq 1 ] && [ ! -z "$VRDL_LATEST_CONTENT_URI" ]; then
	log 0 "Downloading latest Enhanced Version ..."
	
	content_uri=$(curl -s "$VRDL_LATEST_CONTENT_URI" \
			| jq -r ".. | .browser_download_url? // empty" | grep -vi "extended")
	
	wget "$content_uri" -P "$tempdir"

elif [ ! -z $VRDL_STATIC_CONTENT_URI ]; then
	log 0 "Downloading game package at: $VRDL_STATIC_CONTENT_URI ..."
	wget "$VRDL_STATIC_CONTENT_URI" -P "$tempdir"
else
	log 2 "VRDL_LATEST_CONTENT_URI or VRDL_STATIC_CONTENT_URI must be set in .env"
	log 0 "Exiting ..."
	exit 1

fi

# Extract

package_content="$(ls $tempdir | grep '.7z')"
7z x -o"$tempdir_x" "$tempdir/$package_content" 

dirs=$(find "$tempdir_x" -mindepth 1 -maxdepth 1 -type d | wc -l)
if [ "$dirs" -eq 1 ]; then
	dir=$(find "$tempdir_x" -mindepth 1 -maxdepth 1 -type d)
	cp "$dir"/* -r "$VRDL_GAME_DEFAULT_PATH"
else
	cp "$tempdir_x"/* -r "$VRDL_GAME_DEFAULT_PATH"
fi

# Prepare for retrieving dedi support package
rm -r "$tempdir"/*

# If provided dedicated support URI, download and install it

if [ ! -z "$VRDL_SUPPORT_URI" ]; then
    wget -P "$tempdir" "$VRDL_SUPPORT_URI"
	package_dedi="$(ls "$tempdir"/*.7z)"
	7z x -o"$VRDL_GAME_DEFAULT_PATH/System" "$package_dedi" -y
fi

# Cleanup

rm -r "$tempdir"

## Systemd service creation
# Launches $SCCT_DEDI_START script

service_content="
[Unit]
Description=Service for starting and starting SCCT:V R/E Dedicated Servers
BindsTo=default.target
Wants=default.target
After=default.target

[Service]
Type=simple
User="$VRDL_STANDARD_USER"
ExecStart=sh "$VRDL_SCRIPTS_PATH/$VRDL_START"
ExecStop=pkill sway
ExecStop=pkill "$VRDL_RUNNER"
PAMName=Login
Restart=on-failure
RestartSec=1
TimeoutStopSec=10
KillMode=control-group

[Install]
WantedBy=default.target
"

# Remove existing service if found
if [ -e "/etc/systemd/system/$VRDL_SERVICE_NAME.service" ]; then
	log 0 "Removing old existing services ..."
	systemctl stop "$VRDL_SERVICE_NAME"
	systemctl disable "$VRDL_SERVICE_NAME"
	rm "/etc/systemd/system/$VRDL_SERVICE_NAME.service"
fi

log 0 "Creating Systemd service ..."
echo "$service_content" > "/etc/systemd/system/${VRDL_SERVICE_NAME}.service"
log 0 "Reloading Systemd service daemon ..."
systemctl daemon-reload

# Enable systemd service

result=$(prompt "Enable systemd service (auto start on boot)? (y/n)")

if [ $result = "y" ]; then

	log 0 "Enabling Service ..."
	systemctl enable "$VRDL_SERVICE_NAME"
fi

## Disable unattended upgrades

result=$(prompt "Remove unattended upgrades (Ubuntu auto, background server updates)? (y/n)")

if [ $result = "y" ]; then
	log 0 "Removing unattended-upgrades ..."
	apt remove unattended-upgrades -y
fi

## Ensure dirs owned by standard user

chown "$VRDL_STANDARD_USER":"$VRDL_STANDARD_USER" "$VRDL_BASE_PATH" -R

## Reboot (updates and whatnot)

echo "A reboot is recommended"
result_rb=$(prompt "Reboot now? (y/n)")

log 0 "Finished!"

if [ $result_rb = "y" ]; then
	echo "Rebooting ..."
	sleep 2
	reboot
fi

